### ISSUE TITLE
<Github Ed Approval Assistance in 4th Largest School District in US > | <2023 12 13>

### ISSUE THREAD

**Issue by davisjm4** [juanpflores/juanpflores#7]
Hi Juan,

I was referred to you by Oracle's head of Education, Heather Stephens, as I was trying to find someone at Github to support getting it approved in Clark County School District for student usage. She sent me your video: GitHub Education: free programs, technology, and opportunities available for Students.

I teach CS and Game Dev at the #2 school in NV and lead the teacher communities for both in Clark county (4th largest district in the country,) Our district is requiring a data sharing agreement to be in place before it will approve github for student use. I reached out to privacy and was told to contact sales. I have not received a response from Sales. I am hoping you will be able to connect me to someone who can assist.

Thank you for any assistance you can provide,
Josiah Davisson
davisjm4@nv.ccsd.net

**Comment by juanpflores** [comment]
Following up on email
